from music_sep.domain.catalog import (
    DEMUCS_MODEL_DESCRIPTIONS,
    SUPPORTED_INPUT_EXTENSIONS as SUPPORTED_INPUT_EXTENSIONS,
    VISUALIZATION_TYPES,
    WHISPER_MODELS as WHISPER_MODELS,
)

# 保持旧模块公开对象和容器类型兼容。
AVAILABLE_MODELS = dict(DEMUCS_MODEL_DESCRIPTIONS)
VIZ_TYPES = VISUALIZATION_TYPES

# 默认采样率
DEFAULT_SAMPLE_RATE = 44100
